version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3003:3000"
    environment:
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
    depends_on:
      - backend
    mem_limit: 300m
    cpus: 0.5

  backend:
    build: ./backend
    ports:
      - "3005:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    depends_on:
      - postgres
    mem_limit: 100m

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=kairostudio
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=kairos_secure_2024
    volumes:
      - kairos_db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped
    mem_limit: 200m

volumes:
  kairos_db:
